# -*- coding: utf-8 -*-
"""UR12_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/183c9VqGjioo0BBQDQnrnBf9HAWHWabQ9
"""

import numpy as np
import ast
import sys
print('\nUser Input result\n')
print('number of police:'+sys.argv[1]+'\n')
print('number of Node:'+sys.argv[2]+'\n')
print('police position:'+sys.argv[3]+'\n')

I = int(sys.argv[2])
Np = int(sys.argv[1])
np.random.seed(2500)
f = np.random.randint(20, size = (I,I))*10
for i in range(I):
    f[i,i]=0
#print(f)

# drunken driver probability on arc ij
p = (np.random.rand(I,I)).round(1)
for j in range(I):
    p[j,j]=0
#print(p)


N = np.zeros((I,I))
for i in range(I):
    for j in range(I):
        N[i,j] = f[i,j]*p[i,j]
#print(N) 

ra = 0.7
rt = 0.3

c = np.random.randint(10,size=(I,I))
for i in range(I):
    c[i,i] = 0
c_penalty = 100
#print(c)

M = 1000

def get_coords():
    #print ("Enter a list of points. For example (0,0), (0,1), (1,1), (1,0)")
    points = sys.argv[3]

    while True:
        try:
            return list(ast.literal_eval(points))
        except SyntaxError:
            print ("Please enter the coordinates in the format mentioned")


x = np.zeros((I,I))
#input: (0, 1), (1, 4), (2, 3), (3, 1)

inputlist = get_coords()
for i in inputlist:
  x[i[0]][i[1]] = 1
#x[0][1] = 1
#sum(N[i,j] * x[i,j] for i in range(I) for j in range(I))
sum = 0
for i in range(I):
  for j in range(I):
    sum = sum + N[i,j] * x[i,j]
print(sum)